ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPLIES';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AUDITOR';

ALTER TYPE "AuditDomain" ADD VALUE IF NOT EXISTS 'CONTRACTS';
ALTER TYPE "AuditDomain" ADD VALUE IF NOT EXISTS 'INVENTORY';
ALTER TYPE "AuditDomain" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDERS';
ALTER TYPE "AuditDomain" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "AuditDomain" ADD VALUE IF NOT EXISTS 'PEOPLE';
