version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gridone_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - gridone_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: gridone_cache
    ports:
      - "6379:6379"

volumes:
  gridone_pgdata: