import { SetMetadata } from '@nestjs/common';

export const ACCESS_POLICY_METADATA_KEY = 'access_policy_requirements';

export const accessPolicyKeys = [
  'pages.dashboard',
  'pages.proposals',
  'pages.orders',
  'pages.contracts',
  'pages.catalog',
  'pages.clients',
  'pages.equipments',
  'pages.finance',
  'pages.inventory',
  'pages.people',
  'pages.usersControl',
  'pages.tickets',
  'pages.serviceReports',
  'pages.technicianPortal',
  'clients.view',
  'clients.create',
  'clients.update',
  'clients.delete',
  'proposals.view',
  'proposals.create',
  'proposals.update',
  'proposals.approve',
  'proposals.cancel',
  'catalog.viewCosts',
  'catalog.manageItems',
  'catalog.view',
  'catalog.create',
  'catalog.update',
  'catalog.delete',
  'contracts.view',
  'contracts.create',
  'contracts.update',
  'contracts.activate',
  'contracts.cancel',
  'orders.view',
  'orders.create',
  'orders.update',
  'orders.dispatch',
  'orders.finish',
  'orders.cancel',
  'tickets.view',
  'tickets.viewOwn',
  'tickets.create',
  'tickets.update',
  'tickets.assign',
  'tickets.comment',
  'tickets.commentOwn',
  'tickets.convertToOrder',
  'tickets.resolve',
  'tickets.close',
  'tickets.cancel',
  'inventory.view',
  'inventory.create',
  'inventory.update',
  'inventory.reserve',
  'inventory.consume',
  'inventory.adjust',
  'purchaseOrders.view',
  'purchaseOrders.create',
  'purchaseOrders.update',
  'purchaseOrders.approve',
  'purchaseOrders.receive',
  'purchaseOrders.cancel',
  'finance.view',
  'finance.create',
  'finance.update',
  'finance.pay',
  'finance.cancel',
  'finance.reconcile',
  'people.view',
  'people.create',
  'people.update',
  'people.delete',
  'technicians.view',
  'technicians.dispatch',
  'technicians.schedule',
  'technicianWork.view',
  'technicianWork.checkInOut',
  'reports.view',
  'reports.export',
  'settings.view',
  'settings.update',
  'settings.admin',
  'users.manage',
  'users.manageSecurity',
  'users.manageCertifications',
  'users.manageSpecialties',
  'users.manageHierarchy',
  'users.viewLiveLocation',
  'proposals.requestDiscountAboveLimit',
  'proposals.approveBudget',
  'maintenanceOrders.submitVisitReport',
  'maintenanceOrders.approveVisitReport',
  'maintenanceOrders.assignWithOverride',
  'serviceReports.view',
  'serviceReports.create',
  'serviceReports.update',
  'serviceReports.addEvidence',
  'serviceReports.sign',
  'serviceReports.approve',
  'serviceReports.releaseToCustomer',
  'serviceReports.generateDocument',
  'serviceReports.manageShareLinks',
  'serviceReports.cancel',
  'audit.read',
] as const;

export type AccessPolicyKey = (typeof accessPolicyKeys)[number];

export const RequireAccessPolicy = (...keys: AccessPolicyKey[]) =>
  SetMetadata(ACCESS_POLICY_METADATA_KEY, keys);
