CREATE TABLE "control_options" (
  "id" TEXT NOT NULL,
  "group" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "control_options_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "control_options_type_code_key" ON "control_options"("type", "code");
CREATE INDEX "control_options_group_type_isActive_sortOrder_idx"
  ON "control_options"("group", "type", "isActive", "sortOrder");

INSERT INTO "control_options" (
  "id",
  "group",
  "type",
  "code",
  "name",
  "description",
  "sortOrder",
  "isActive"
) VALUES
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'UN', 'Unidade', 'Unidade individual de peca ou produto.', 10, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'PC', 'Peca', 'Peca individual.', 20, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'JG', 'Jogo', 'Conjunto vendido como jogo.', 30, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'KIT', 'Kit', 'Kit tecnico ou comercial.', 40, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'LT', 'Litro', 'Medida para oleos, aditivos e fluidos.', 50, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'KG', 'Quilograma', 'Medida por peso.', 60, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'M', 'Metro', 'Medida linear.', 70, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'H', 'Hora', 'Unidade para servicos por hora.', 80, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_UNIT', 'SERV', 'Servico', 'Unidade para servicos de preco fechado.', 90, true),

  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'MANN', 'Mann-Filter', 'Marca de filtros e componentes.', 10, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'FLEETGUARD', 'Fleetguard', 'Marca de filtros e componentes.', 20, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'DONALDSON', 'Donaldson', 'Marca de filtros e componentes.', 30, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'PARKER', 'Parker', 'Marca de filtros, mangueiras e componentes.', 40, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'WEG', 'WEG', 'Marca eletrica e alternadores.', 50, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'STEMAC', 'Stemac', 'Marca de grupos geradores.', 60, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'CUMMINS', 'Cummins', 'Marca de motores e componentes.', 70, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'PERKINS', 'Perkins', 'Marca de motores e componentes.', 80, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'MWM', 'MWM', 'Marca de motores e componentes.', 90, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_BRAND', 'OTHER', 'Outra marca', 'Opcao temporaria quando a marca ainda nao foi cadastrada.', 999, true),

  (gen_random_uuid()::text, 'catalog', 'CATALOG_DOCUMENT_CATEGORY', 'DATASHEET', 'Ficha tecnica', 'Documento tecnico do item.', 10, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_DOCUMENT_CATEGORY', 'MANUAL', 'Manual', 'Manual de uso, instalacao ou manutencao.', 20, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_DOCUMENT_CATEGORY', 'CERTIFICATE', 'Certificado', 'Certificado, laudo ou documento de conformidade.', 30, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_DOCUMENT_CATEGORY', 'FISCAL', 'Documento fiscal', 'NCM, CEST, origem ou referencia fiscal.', 40, true),
  (gen_random_uuid()::text, 'catalog', 'CATALOG_DOCUMENT_CATEGORY', 'IMAGE', 'Imagem', 'Foto ou imagem comercial do item.', 50, true),

  (gen_random_uuid()::text, 'catalog', 'STORAGE_LOCATION', 'ALM-PRINCIPAL', 'Almoxarifado principal', 'Local principal de estoque.', 10, true),
  (gen_random_uuid()::text, 'catalog', 'STORAGE_LOCATION', 'BANCADA', 'Bancada tecnica', 'Itens em bancada ou separacao.', 20, true),
  (gen_random_uuid()::text, 'catalog', 'STORAGE_LOCATION', 'VEICULO', 'Veiculo tecnico', 'Estoque movel em veiculo.', 30, true),
  (gen_random_uuid()::text, 'catalog', 'STORAGE_LOCATION', 'OBRA', 'Obra ou cliente', 'Item alocado temporariamente em campo.', 40, true),

  (gen_random_uuid()::text, 'operation', 'SERVICE_TYPE', 'TERMOGRAFIA', 'Termografia', 'Servico de inspecao termografica.', 10, true),
  (gen_random_uuid()::text, 'operation', 'SERVICE_TYPE', 'PREVENTIVA', 'Manutencao preventiva', 'Servico preventivo programado.', 20, true),
  (gen_random_uuid()::text, 'operation', 'SERVICE_TYPE', 'CORRETIVA', 'Manutencao corretiva', 'Servico corretivo por falha ou anomalia.', 30, true),
  (gen_random_uuid()::text, 'operation', 'SERVICE_TYPE', 'COMISSIONAMENTO', 'Comissionamento', 'Start-up, testes e liberacao tecnica.', 40, true),
  (gen_random_uuid()::text, 'operation', 'SERVICE_TYPE', 'INSTALACAO', 'Instalacao', 'Instalacao, montagem ou adequacao.', 50, true),
  (gen_random_uuid()::text, 'operation', 'SERVICE_TYPE', 'VISITA_TECNICA', 'Visita tecnica', 'Diagnostico, levantamento ou apoio tecnico.', 60, true),

  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TYPE', 'PREVENTIVE', 'Preventiva', 'Manutencao planejada por prazo ou horimetro.', 10, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TYPE', 'CORRECTIVE', 'Corretiva', 'Manutencao para correcao de falha.', 20, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TYPE', 'INSTALLATION', 'Instalacao', 'Instalacao ou montagem tecnica.', 30, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TYPE', 'DEMOBILIZATION', 'Desmobilizacao', 'Retirada ou encerramento operacional.', 40, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TYPE', 'REFUELING', 'Abastecimento', 'Atendimento de abastecimento.', 50, true),

  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'OIL', 'Oleo', 'Itens de oleo e lubrificacao.', 10, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'FILTER', 'Filtros', 'Troca ou verificacao de filtros.', 20, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'BATTERY', 'Baterias', 'Inspecao, troca ou teste de baterias.', 30, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'INSPECTION', 'Inspecao', 'Checklist de inspecao geral.', 40, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'TEST', 'Teste', 'Testes funcionais e operacionais.', 50, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'CLEANING', 'Limpeza', 'Limpeza tecnica e conservacao.', 60, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'ELECTRICAL', 'Eletrica', 'Itens eletricos e comandos.', 70, true),
  (gen_random_uuid()::text, 'operation', 'MAINTENANCE_TEMPLATE_CATEGORY', 'MECHANICAL', 'Mecanica', 'Itens mecanicos.', 80, true),

  (gen_random_uuid()::text, 'operation', 'TICKET_CATEGORY', 'CORRECTIVE_MAINTENANCE', 'Manutencao corretiva', 'Chamado de manutencao corretiva.', 10, true),
  (gen_random_uuid()::text, 'operation', 'TICKET_CATEGORY', 'PREVENTIVE_REQUEST', 'Solicitacao preventiva', 'Pedido de manutencao preventiva.', 20, true),
  (gen_random_uuid()::text, 'operation', 'TICKET_CATEGORY', 'EMERGENCY', 'Emergencia', 'Chamado emergencial.', 30, true),
  (gen_random_uuid()::text, 'operation', 'TICKET_CATEGORY', 'QUOTE_REQUEST', 'Solicitacao de cotacao', 'Pedido de proposta ou orcamento.', 40, true),
  (gen_random_uuid()::text, 'operation', 'TICKET_CATEGORY', 'DOCUMENT_REQUEST', 'Solicitacao de documento', 'Pedido de documento tecnico ou fiscal.', 50, true),
  (gen_random_uuid()::text, 'operation', 'TICKET_CATEGORY', 'TECHNICAL_SUPPORT', 'Suporte tecnico', 'Apoio tecnico sem OS imediata.', 60, true),

  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_APPLICATION', 'STANDBY', 'Standby', 'Gerador para emergencia ou backup.', 10, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_APPLICATION', 'PRIME', 'Prime', 'Gerador como fonte principal por periodos longos.', 20, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_APPLICATION', 'CONTINUOUS', 'Continuo', 'Operacao continua.', 30, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_APPLICATION', 'PEAK_SHAVING', 'Horario de ponta', 'Operacao para controle de demanda ou ponta.', 40, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_APPLICATION', 'RENTAL', 'Locacao', 'Aplicacao em equipamento locado.', 50, true),

  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_OPERATION_MODE', 'MANUAL', 'Manual', 'Operacao manual.', 10, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_OPERATION_MODE', 'AUTOMATIC', 'Automatico', 'Operacao automatica com transferencia.', 20, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_OPERATION_MODE', 'PARALLEL', 'Paralelo', 'Operacao em paralelo.', 30, true),
  (gen_random_uuid()::text, 'assets', 'EQUIPMENT_OPERATION_MODE', 'REMOTE', 'Remoto', 'Operacao ou monitoramento remoto.', 40, true),

  (gen_random_uuid()::text, 'people', 'HR_ASSET_CATEGORY', 'EPI', 'EPI', 'Equipamento de protecao individual.', 10, true),
  (gen_random_uuid()::text, 'people', 'HR_ASSET_CATEGORY', 'TOOL', 'Ferramenta tecnica', 'Ferramenta entregue ao tecnico.', 20, true),
  (gen_random_uuid()::text, 'people', 'HR_ASSET_CATEGORY', 'INTERNAL_SUPPLY', 'Uso interno', 'Material de consumo interno: fita, papel, pilha e similares.', 30, true),
  (gen_random_uuid()::text, 'people', 'HR_ASSET_CATEGORY', 'GENERATOR_PART', 'Peca de gerador', 'Peca aplicada em geradores.', 40, true),

  (gen_random_uuid()::text, 'finance', 'PAYMENT_TERM', 'A_VISTA', 'A vista', 'Pagamento a vista.', 10, true),
  (gen_random_uuid()::text, 'finance', 'PAYMENT_TERM', '7_DIAS', '7 dias', 'Pagamento em 7 dias.', 20, true),
  (gen_random_uuid()::text, 'finance', 'PAYMENT_TERM', '14_DIAS', '14 dias', 'Pagamento em 14 dias.', 30, true),
  (gen_random_uuid()::text, 'finance', 'PAYMENT_TERM', '21_DIAS', '21 dias', 'Pagamento em 21 dias.', 40, true),
  (gen_random_uuid()::text, 'finance', 'PAYMENT_TERM', '30_DIAS', '30 dias', 'Pagamento em 30 dias.', 50, true),
  (gen_random_uuid()::text, 'finance', 'PAYMENT_TERM', '30_60_DIAS', '30/60 dias', 'Pagamento parcelado em 30/60 dias.', 60, true),

  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'AC', 'Acre', NULL, 10, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'AL', 'Alagoas', NULL, 20, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'AP', 'Amapa', NULL, 30, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'AM', 'Amazonas', NULL, 40, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'BA', 'Bahia', NULL, 50, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'CE', 'Ceara', NULL, 60, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'DF', 'Distrito Federal', NULL, 70, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'ES', 'Espirito Santo', NULL, 80, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'GO', 'Goias', NULL, 90, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'MA', 'Maranhao', NULL, 100, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'MT', 'Mato Grosso', NULL, 110, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'MS', 'Mato Grosso do Sul', NULL, 120, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'MG', 'Minas Gerais', NULL, 130, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'PA', 'Para', NULL, 140, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'PB', 'Paraiba', NULL, 150, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'PR', 'Parana', NULL, 160, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'PE', 'Pernambuco', NULL, 170, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'PI', 'Piaui', NULL, 180, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'RJ', 'Rio de Janeiro', NULL, 190, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'RN', 'Rio Grande do Norte', NULL, 200, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'RS', 'Rio Grande do Sul', NULL, 210, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'RO', 'Rondonia', NULL, 220, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'RR', 'Roraima', NULL, 230, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'SC', 'Santa Catarina', NULL, 240, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'SP', 'Sao Paulo', NULL, 250, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'SE', 'Sergipe', NULL, 260, true),
  (gen_random_uuid()::text, 'address', 'BRAZIL_STATE', 'TO', 'Tocantins', NULL, 270, true)
ON CONFLICT ("type", "code") DO NOTHING;
