ALTER TYPE "ApprovalType" ADD VALUE IF NOT EXISTS 'CATALOG_PRICING';

ALTER TABLE "approval_requests"
ADD COLUMN IF NOT EXISTS "requestPayload" JSONB;

ALTER TABLE "catalog_pricing_policies"
ADD COLUMN IF NOT EXISTS "icmsPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "pisPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "cofinsPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "ipiPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "issPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "irpjPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "csllPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "cppPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
